input_income = int(input("Welcome to the Income Tax Calculator! Please input your annual income: "))
i = 0
while i == 0:
    input_province = input("Please input the province you currently reside in (ON/QC/AB): ")
    if input_province == "ON" or input_province == "QC" or input_province == "AB":
        i += 1
    else:
        print("Please input a valid province.")

#Federal Tax Brackets (2023)
FIRST_FEDERAL_TAX_BRACKET_LIMIT=53359
SECOND_FEDERAL_TAX_BRACKET_LIMIT=106717
THIRD_FEDERAL_TAX_BRACKET_LIMIT=164914
FOURTH_FEDERAL_TAX_BRACKET_LIMIT=234609

#Federal Tax Rates (2023)
FIRST_FEDERAL_TAX_RATE=0.15
SECOND_FEDERAL_TAX_RATE=0.205
THIRD_FEDERAL_TAX_RATE=0.26
FOURTH_FEDERAL_TAX_RATE=0.29
FIFTH_FEDERAL_TAX_RATE=0.33

def calculate_federal_tax(income):
    federal_tax = 0
    if income <= FIRST_FEDERAL_TAX_BRACKET_LIMIT:
        federal_tax = income*FIRST_FEDERAL_TAX_RATE
    elif income > FIRST_FEDERAL_TAX_BRACKET_LIMIT and income <= SECOND_FEDERAL_TAX_BRACKET_LIMIT:
        federal_tax = FIRST_FEDERAL_TAX_BRACKET_LIMIT*FIRST_FEDERAL_TAX_RATE+(income-FIRST_FEDERAL_TAX_BRACKET_LIMIT)*SECOND_FEDERAL_TAX_RATE
    elif income > SECOND_FEDERAL_TAX_BRACKET_LIMIT and income <= THIRD_FEDERAL_TAX_BRACKET_LIMIT:
        federal_tax = FIRST_FEDERAL_TAX_BRACKET_LIMIT*FIRST_FEDERAL_TAX_RATE+(SECOND_FEDERAL_TAX_BRACKET_LIMIT-FIRST_FEDERAL_TAX_BRACKET_LIMIT)*SECOND_FEDERAL_TAX_RATE+(income-SECOND_FEDERAL_TAX_BRACKET_LIMIT)*THIRD_FEDERAL_TAX_RATE
    elif income > THIRD_FEDERAL_TAX_BRACKET_LIMIT and income <= FOURTH_FEDERAL_TAX_BRACKET_LIMIT:
        federal_tax = FIRST_FEDERAL_TAX_BRACKET_LIMIT*FIRST_FEDERAL_TAX_RATE+(SECOND_FEDERAL_TAX_BRACKET_LIMIT-FIRST_FEDERAL_TAX_BRACKET_LIMIT)*SECOND_FEDERAL_TAX_RATE+(THIRD_FEDERAL_TAX_BRACKET_LIMIT-SECOND_FEDERAL_TAX_BRACKET_LIMIT)*THIRD_FEDERAL_TAX_RATE+(income-THIRD_FEDERAL_TAX_BRACKET_LIMIT)*FOURTH_FEDERAL_TAX_RATE
    else:
        federal_tax = FIRST_FEDERAL_TAX_BRACKET_LIMIT*FIRST_FEDERAL_TAX_RATE+(SECOND_FEDERAL_TAX_BRACKET_LIMIT-FIRST_FEDERAL_TAX_BRACKET_LIMIT)*SECOND_FEDERAL_TAX_RATE+(THIRD_FEDERAL_TAX_BRACKET_LIMIT-SECOND_FEDERAL_TAX_BRACKET_LIMIT)*THIRD_FEDERAL_TAX_RATE+(FOURTH_FEDERAL_TAX_BRACKET_LIMIT-THIRD_FEDERAL_TAX_BRACKET_LIMIT)*FOURTH_FEDERAL_TAX_RATE+(income-FOURTH_FEDERAL_TAX_BRACKET_LIMIT)*FIFTH_FEDERAL_TAX_RATE
    
    return round(federal_tax,2)

#ON Provincial Tax Brackets (2023)
FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT=47630
SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT=95259
THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT=107838
FOURTH_PROVINCIAL_ON_TAX_BRACKET_LIMIT=129361

#ON Provincial Tax Rates (2023)
FIRST_PROVINCIAL_ON_TAX_RATE=0.0505
SECOND_PROVINCIAL_ON_TAX_RATE=0.0915
THIRD_PROVINCIAL_ON_TAX_RATE=0.1116
FOURTH_PROVINCIAL_ON_TAX_RATE=0.1216
FIFTH_PROVINCIAL_ON_TAX_RATE=0.1316

#QC Provincial Tax Brackets (2023)
FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT=49275
SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT=98540
THIRD_PROVINCIAL_QC_TAX_BRACKET_LIMIT=117850

#QC Provincial Tax Rates (2023)
FIRST_PROVINCIAL_QC_TAX_RATE=0.15
SECOND_PROVINCIAL_QC_TAX_RATE=0.20
THIRD_PROVINCIAL_QC_TAX_RATE=0.24
FOURTH_PROVINCIAL_QC_TAX_RATE=0.2575

#AB Provincial Tax Brackets (2023)
FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT=142292
SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT=168437
THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT=220728
FOURTH_PROVINCIAL_AB_TAX_BRACKET_LIMIT=325301

#AB Provincial Tax Rates (2023)
FIRST_PROVINCIAL_AB_TAX_RATE=0.10
SECOND_PROVINCIAL_AB_TAX_RATE=0.12
THIRD_PROVINCIAL_AB_TAX_RATE=0.13
FOURTH_PROVINCIAL_AB_TAX_RATE=0.14
FIFTH_PROVINCIAL_AB_TAX_RATE=0.15

def calculate_provincial_tax(province,income):
    provincial_tax = 0
    if province == "ON":
        if income <= FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT:
            provincial_tax = income*FIRST_PROVINCIAL_ON_TAX_RATE
        elif income > FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT and income <= SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_ON_TAX_RATE+(income-FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_ON_TAX_RATE
        elif income > SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT and income <= THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_ON_TAX_RATE+(SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_ON_TAX_RATE+(income-SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_ON_TAX_RATE
        elif income > THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT and income <= FOURTH_PROVINCIAL_ON_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_ON_TAX_RATE+(SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_ON_TAX_RATE+(THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT-SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_ON_TAX_RATE+(income-THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*FOURTH_PROVINCIAL_ON_TAX_RATE
        else:
            provincial_tax = FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_ON_TAX_RATE+(SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_ON_TAX_RATE+(THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT-SECOND_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_ON_TAX_RATE+(FOURTH_PROVINCIAL_ON_TAX_BRACKET_LIMIT-THIRD_PROVINCIAL_ON_TAX_BRACKET_LIMIT)*FOURTH_PROVINCIAL_ON_TAX_RATE+(income-FOURTH_PROVINCIAL_ON_TAX_RATE)*FIFTH_PROVINCIAL_ON_TAX_RATE
        
    if province == "QC":
        if income <= FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT:
            provincial_tax = income*FIRST_PROVINCIAL_QC_TAX_RATE
        elif income > FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT and income <= SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_QC_TAX_RATE+(income-FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_QC_TAX_RATE
        elif income > SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT and income <= THIRD_PROVINCIAL_QC_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_QC_TAX_RATE+(SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_QC_TAX_RATE+(income-SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_QC_TAX_RATE
        else:
            provincial_tax = FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_QC_TAX_RATE+(SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_QC_TAX_RATE+(THIRD_PROVINCIAL_QC_TAX_BRACKET_LIMIT-SECOND_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_QC_TAX_RATE+(income-THIRD_PROVINCIAL_QC_TAX_BRACKET_LIMIT)*FOURTH_PROVINCIAL_QC_TAX_RATE

    if province == "AB":
        if income <= FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT:
            provincial_tax = income*FIRST_PROVINCIAL_AB_TAX_RATE
        elif income > FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT and income <= SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_AB_TAX_RATE+(income-FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_AB_TAX_RATE
        elif income > SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT and income <= THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_AB_TAX_RATE+(SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_AB_TAX_RATE+(income-SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_AB_TAX_RATE
        elif income > THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT and income <= FOURTH_PROVINCIAL_AB_TAX_BRACKET_LIMIT:
            provincial_tax = FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_AB_TAX_RATE+(SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_AB_TAX_RATE+(THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT-SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_AB_TAX_RATE+(income-THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*FOURTH_PROVINCIAL_AB_TAX_RATE
        else:
            provincial_tax = FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT*FIRST_PROVINCIAL_AB_TAX_RATE+(SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT-FIRST_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*SECOND_PROVINCIAL_AB_TAX_RATE+(THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT-SECOND_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*THIRD_PROVINCIAL_AB_TAX_RATE+(FOURTH_PROVINCIAL_AB_TAX_BRACKET_LIMIT-THIRD_PROVINCIAL_AB_TAX_BRACKET_LIMIT)*FOURTH_PROVINCIAL_AB_TAX_RATE+(income-FOURTH_PROVINCIAL_AB_TAX_RATE)*FIFTH_PROVINCIAL_AB_TAX_RATE
        
    return round(provincial_tax,2)

#Outputs
print("The federal tax is $" + str(calculate_federal_tax(input_income)))
print(f"The provincial tax for {input_province} is $" + str(calculate_provincial_tax(input_province,input_income)))
print("The total tax owed is $" + str(calculate_federal_tax(input_income) + calculate_provincial_tax(input_province,input_income)))
    